steps:

- name:	'gcr.io/cloud-builders/git'
  id: 'Clone'
  args: ['clone','https://github.com/gadkari-vinayak/santosh.git']

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/helloworld:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'gcr.io/$PROJECT_ID/helloworld:$SHORT_SHA']
