steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/santosh:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/santosh:$SHORT_SHA']
 steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'santosh', '--image=gcr.io/$PROJECT_ID/santosh', '--region=us-central1']
  images:
- gcr.io/$PROJECT_ID/santosh:$SHORT_SHA
